[[libpcap]]
arch = "aarch64"
git-tree-sha1 = "ada59aee2374aea6c046114c2c1a7b31e073251d"
libc = "glibc"
os = "linux"

    [[libpcap.download]]
    sha256 = "86fa97467111f2874a7aa77d49b0a97ef0ef7dab95cbbb867d389d6c83e4add3"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.aarch64-linux-gnu.tar.gz"
[[libpcap]]
arch = "aarch64"
git-tree-sha1 = "767e335a3443fdeb1d41e2ca8fe423ff85f902b9"
libc = "musl"
os = "linux"

    [[libpcap.download]]
    sha256 = "8081c5018c82dd1e987fe469948fc0b8d5c554e3435c5523bf3081c78a78bd98"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.aarch64-linux-musl.tar.gz"
[[libpcap]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "21e526bb0ef260c76a1c9912d7e1b498e2d0f0bb"
libc = "glibc"
os = "linux"

    [[libpcap.download]]
    sha256 = "6eabafc690a92760578dec8e06fb691fac6d93fbf82e4c5c0a9f06ab2fdf00f7"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.armv6l-linux-gnueabihf.tar.gz"
[[libpcap]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1c54a203067eefceb1edc83dbdf66a0dad1c735d"
libc = "musl"
os = "linux"

    [[libpcap.download]]
    sha256 = "59df0c04b3427fe4a0436e24df3944a6a69cc7189c45bded5fb3b9f1f311a677"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.armv6l-linux-musleabihf.tar.gz"
[[libpcap]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4c61dc2967575077fbe49ce966b3db385ba0b06"
libc = "glibc"
os = "linux"

    [[libpcap.download]]
    sha256 = "7fd777a27c032a943bb0cb58fff13f81d39794664f02c37d8932e11abc025770"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.armv7l-linux-gnueabihf.tar.gz"
[[libpcap]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce7246a4b0abca5d303afc1f7b9927c7044f1b8e"
libc = "musl"
os = "linux"

    [[libpcap.download]]
    sha256 = "4ce86aaf79899168d41ab6ab1653aa1126cfe355e9cb8fb87386528fbc28b303"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.armv7l-linux-musleabihf.tar.gz"
[[libpcap]]
arch = "i686"
git-tree-sha1 = "cb7f05fc6b026aaf9f64b9dacf200d5d7604104f"
libc = "glibc"
os = "linux"

    [[libpcap.download]]
    sha256 = "088029f1886da5622de825eaf79100e854cb340e9f94b6720cfcea75a44c8218"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.i686-linux-gnu.tar.gz"
[[libpcap]]
arch = "i686"
git-tree-sha1 = "1d4bd6abac88b725718773a7fbc465f7135e065c"
libc = "musl"
os = "linux"

    [[libpcap.download]]
    sha256 = "cb86a9a69d818d2da0fe9a9ff7867521ffe4ea7dee3ffb2c7963d19c0b5e54a8"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.i686-linux-musl.tar.gz"
[[libpcap]]
arch = "powerpc64le"
git-tree-sha1 = "edbcb26ea381ed105c2ea12cc82e4fd4b3c1820b"
libc = "glibc"
os = "linux"

    [[libpcap.download]]
    sha256 = "d620d7839ca261babb6ff23d877aa14bf62cbca2ed389c95cb748b389223d133"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.powerpc64le-linux-gnu.tar.gz"
[[libpcap]]
arch = "x86_64"
git-tree-sha1 = "5199d6c2c7d758acd64f1dd8cfa3eed5499a3d28"
os = "macos"

    [[libpcap.download]]
    sha256 = "120594f4c09abad96fa0e8b413cf2fa3d3779c34532dfb950a795cbb5c802f1e"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.x86_64-apple-darwin.tar.gz"
[[libpcap]]
arch = "x86_64"
git-tree-sha1 = "0c82f41d5a5e9e86ddd6b37667b099c35c2cadaa"
libc = "glibc"
os = "linux"

    [[libpcap.download]]
    sha256 = "2b4388de15c84b3338b4d1646baabbb3d7c7bfebe73b13cd32da89077a0eb38f"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.x86_64-linux-gnu.tar.gz"
[[libpcap]]
arch = "x86_64"
git-tree-sha1 = "fda4a730d19e7e8c3518a66dd434869f07527f7e"
libc = "musl"
os = "linux"

    [[libpcap.download]]
    sha256 = "0bcea9088a61b0750d9c375e37da74c4d4041efc8fa0080cafbc811ef804d880"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.x86_64-linux-musl.tar.gz"
[[libpcap]]
arch = "x86_64"
git-tree-sha1 = "555ab53a27a5417277581b4d7f529a64b180d538"
os = "freebsd"

    [[libpcap.download]]
    sha256 = "48b994b9326197e89327c36b362f9c48b55510cff284e87ac82de9001eb035c2"
    url = "https://github.com/JuliaBinaryWrappers/libpcap_jll.jl/releases/download/libpcap-v1.10.4+0/libpcap.v1.10.4.x86_64-unknown-freebsd.tar.gz"
